import type { CoursesResponse } from '@/types/course'
import type {
  EnrolledCourse,
  UpcomingClass,
  DashboardStats,
  RecentActivity,
  Announcement,
  Instructor,
  BlogPost,
  LiveClass,
} from '@/types/dashboard'

// Mock data for development when API is unavailable
export const mockCoursesResponse: CoursesResponse = {
  success: true,
  message: 'Courses retrieved successfully (MOCK DATA)',
  data: {
    courses: [
      {
        id: 1,
        name: 'NEET UG 2025',
        description: 'Comprehensive preparation course for NEET UG entrance examination',
        duration_months: 12,
        is_active: true,
        image_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=300&fit=crop',
        category: {
          id: 1,
          name: 'Medical',
          slug: 'medical',
          description: 'Medical entrance exam category',
          icon: 'medical-icon.svg',
        },
        subjects_count: 4,
        questions_count: 2000,
        total_chapters: 52,
        difficulty_level: 'advanced',
      },
      {
        id: 2,
        name: 'JEE Main 2025',
        description: 'Complete preparation for JEE Main entrance examination',
        duration_months: 12,
        is_active: true,
        image_url: 'https://images.unsplash.com/photo-1581092335331-5e00ac65e934?w=400&h=300&fit=crop',
        category: {
          id: 2,
          name: 'Engineering',
          slug: 'engineering',
          description: 'Engineering entrance exam category',
          icon: 'engineering-icon.svg',
        },
        subjects_count: 3,
        questions_count: 1500,
        total_chapters: 45,
        difficulty_level: 'intermediate',
      },
      {
        id: 3,
        name: 'AWS Cloud Practitioner',
        description: 'Prepare for AWS Certified Cloud Practitioner certification',
        duration_months: 3,
        is_active: true,
        image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=300&fit=crop',
        category: {
          id: 3,
          name: 'IT & Cloud',
          slug: 'it-cloud',
          description: 'IT and Cloud certification category',
          icon: 'cloud-icon.svg',
        },
        subjects_count: 5,
        questions_count: 800,
        total_chapters: 20,
        difficulty_level: 'beginner',
      },
    ],
  },
}

// Dashboard Mock Data
export const mockDashboardStats: DashboardStats = {
  totalCourses: 5,
  completedCourses: 2,
  hoursLearned: 127,
  studyStreak: 12,
  averageScore: 87,
  testsCompleted: 24,
}

export const mockRecentTestScores = [
  {
    id: 1,
    testName: 'Physics Mock Test #12',
    score: 92,
    totalQuestions: 50,
    correctAnswers: 46,
    date: '2024-01-14T18:45:00',
    subject: 'Physics',
  },
  {
    id: 2,
    testName: 'Chemistry Practice Test',
    score: 85,
    totalQuestions: 40,
    correctAnswers: 34,
    date: '2024-01-12T16:30:00',
    subject: 'Chemistry',
  },
  {
    id: 3,
    testName: 'Biology Mock Test #8',
    score: 88,
    totalQuestions: 45,
    correctAnswers: 40,
    date: '2024-01-10T14:20:00',
    subject: 'Biology',
  },
]

export const mockAchievements = [
  {
    id: 1,
    title: 'First Steps',
    description: 'Complete your first lesson',
    icon: 'flag-checkered',
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    unlocked: true,
    date: '2024-01-05',
  },
  {
    id: 2,
    title: 'Week Warrior',
    description: 'Maintain 7-day streak',
    icon: 'fire',
    color: 'text-orange-600',
    bgColor: 'bg-orange-100',
    unlocked: true,
    date: '2024-01-12',
  },
  {
    id: 3,
    title: 'Quiz Master',
    description: 'Score 90%+ in 5 tests',
    icon: 'trophy',
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
    unlocked: false,
    progress: 60,
  },
  {
    id: 4,
    title: 'Course Completer',
    description: 'Finish your first course',
    icon: 'graduation-cap',
    color: 'text-green-600',
    bgColor: 'bg-green-100',
    unlocked: true,
    date: '2024-01-10',
  },
  {
    id: 5,
    title: 'Study Marathon',
    description: 'Study for 100 hours',
    icon: 'clock',
    color: 'text-purple-600',
    bgColor: 'bg-purple-100',
    unlocked: false,
    progress: 75,
  },
  {
    id: 6,
    title: 'Perfect Score',
    description: 'Get 100% in a test',
    icon: 'star',
    color: 'text-pink-600',
    bgColor: 'bg-pink-100',
    unlocked: false,
    progress: 0,
  },
]

export const mockLearningGoals = [
  {
    id: 1,
    title: 'Daily Study Time',
    target: 4,
    current: 2.5,
    unit: 'hours/day',
    icon: 'clock',
    color: 'blue',
    deadline: 'Daily Goal',
  },
  {
    id: 2,
    title: 'Weekly Tests',
    target: 5,
    current: 3,
    unit: 'tests',
    icon: 'clipboard-list',
    color: 'green',
    deadline: 'This Week',
  },
  {
    id: 3,
    title: 'Course Completion',
    target: 3,
    current: 2,
    unit: 'courses',
    icon: 'book',
    color: 'purple',
    deadline: 'This Month',
  },
]

export const mockWeeklyActivity = [
  { day: 'Mon', hours: 3.5, date: 'Jan 15' },
  { day: 'Tue', hours: 4.2, date: 'Jan 16' },
  { day: 'Wed', hours: 2.8, date: 'Jan 17' },
  { day: 'Thu', hours: 5.1, date: 'Jan 18' },
  { day: 'Fri', hours: 3.9, date: 'Jan 19' },
  { day: 'Sat', hours: 1.5, date: 'Jan 20' },
  { day: 'Sun', hours: 0.8, date: 'Jan 21' },
]

export const mockPersonalizedInsights = [
  {
    id: 1,
    type: 'success' as const,
    title: 'Great Progress!',
    message: 'You\'re 25% ahead of your weekly study goal. Keep up the excellent work!',
  },
  {
    id: 2,
    type: 'tip' as const,
    title: 'Study Tip',
    message: 'Your best performance is in morning sessions. Try scheduling important topics between 9-11 AM.',
  },
  {
    id: 3,
    type: 'warning' as const,
    title: 'Upcoming Deadline',
    message: 'You have 3 pending assignments due this week. Complete them to stay on track.',
    action: {
      label: 'View Assignments',
      link: '/my-courses',
    },
  },
  {
    id: 4,
    type: 'info' as const,
    title: 'New Course Recommendation',
    message: 'Based on your progress, we recommend "Advanced Physics" to complement your current studies.',
    action: {
      label: 'Explore Course',
      link: '/courses',
    },
  },
]

export const mockRecommendedCourses = [
  {
    id: 4,
    name: 'Advanced Physics for JEE',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=300&fit=crop',
    category: 'Engineering',
    instructor: 'Dr. Sarah Johnson',
    rating: 4.7,
    students: 3200,
    price: 4999,
  },
  {
    id: 5,
    name: 'Organic Chemistry Mastery',
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=400&h=300&fit=crop',
    category: 'Medical',
    instructor: 'Prof. Michael Chen',
    rating: 4.9,
    students: 4500,
    price: 5999,
  },
]

export const mockEnrolledCourses: EnrolledCourse[] = [
  {
    id: 1,
    courseId: 1,
    courseName: 'NEET UG 2025',
    courseImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=300&fit=crop',
    category: 'Medical',
    progress: 65,
    totalLessons: 120,
    completedLessons: 78,
    lastAccessed: '2024-01-15T10:30:00',
    instructor: 'Dr. Rajesh Kumar',
    status: 'in-progress',
    rating: 4.5,
  },
  {
    id: 2,
    courseId: 2,
    courseName: 'JEE Main 2025',
    courseImage: 'https://images.unsplash.com/photo-1581092335331-5e00ac65e934?w=400&h=300&fit=crop',
    category: 'Engineering',
    progress: 45,
    totalLessons: 100,
    completedLessons: 45,
    lastAccessed: '2024-01-14T15:20:00',
    instructor: 'Prof. Amit Sharma',
    status: 'in-progress',
    rating: 4.8,
  },
  {
    id: 3,
    courseId: 3,
    courseName: 'AWS Cloud Practitioner',
    courseImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=300&fit=crop',
    category: 'IT & Cloud',
    progress: 100,
    totalLessons: 50,
    completedLessons: 50,
    lastAccessed: '2024-01-10T09:00:00',
    instructor: 'John Anderson',
    status: 'completed',
    certificateUrl: '/certificates/aws-cloud-practitioner.pdf',
    rating: 5.0,
  },
]

export const mockUpcomingClasses: UpcomingClass[] = [
  {
    id: 1,
    title: 'Organic Chemistry - Advanced Concepts',
    instructor: 'Dr. Rajesh Kumar',
    instructorImage: 'https://i.pravatar.cc/150?u=rajesh',
    courseName: 'NEET UG 2025',
    startTime: '2024-01-16T14:00:00',
    duration: 90,
    meetingLink: 'https://meet.ebodhak.com/organic-chem-101',
    isLive: false,
  },
  {
    id: 2,
    title: 'Calculus Problem Solving',
    instructor: 'Prof. Amit Sharma',
    instructorImage: 'https://i.pravatar.cc/150?u=amit',
    courseName: 'JEE Main 2025',
    startTime: '2024-01-16T16:30:00',
    duration: 60,
    meetingLink: 'https://meet.ebodhak.com/calculus-session',
    isLive: false,
  },
]

export const mockRecentActivity: RecentActivity[] = [
  {
    id: 1,
    type: 'course',
    title: 'Completed Chapter 5',
    description: 'Organic Chemistry - NEET UG 2025',
    timestamp: '2024-01-15T10:30:00',
    icon: 'book-open',
  },
  {
    id: 2,
    type: 'test',
    title: 'Scored 92%',
    description: 'Physics Mock Test #12',
    timestamp: '2024-01-14T18:45:00',
    icon: 'trophy',
  },
  {
    id: 3,
    type: 'achievement',
    title: 'Achievement Unlocked',
    description: '7-day study streak!',
    timestamp: '2024-01-14T08:00:00',
    icon: 'award',
  },
]

export const mockAnnouncements: Announcement[] = [
  {
    id: 1,
    title: 'New Course Available',
    message: 'AWS Solutions Architect course is now live!',
    type: 'success',
    date: '2024-01-15T09:00:00',
    isRead: false,
  },
  {
    id: 2,
    title: 'Scheduled Maintenance',
    message: 'Platform will be under maintenance on Jan 20, 2024 from 2-4 AM',
    type: 'warning',
    date: '2024-01-14T10:00:00',
    isRead: false,
  },
]

export const mockInstructors: Instructor[] = [
  {
    id: 1,
    name: 'Dr. Rajesh Kumar',
    title: 'Medical Sciences Expert',
    bio: 'Dr. Rajesh Kumar is a renowned medical educator with over 15 years of experience in preparing students for NEET and medical entrance exams. His innovative teaching methods have helped thousands of students achieve their dreams.',
    image: 'https://i.pravatar.cc/400?u=rajesh-kumar',
    expertise: ['Biology', 'Chemistry', 'Medical Sciences', 'NEET Preparation'],
    experience: 15,
    students: 5200,
    courses: 12,
    rating: 4.9,
    totalReviews: 1250,
    education: ['MBBS - AIIMS Delhi', 'MD - Internal Medicine', 'PhD - Medical Education'],
    certifications: ['Medical Education Specialist', 'NEET Expert Trainer'],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/rajesh-kumar',
      youtube: 'https://youtube.com/@drrajeshkumar',
    },
    videoIntro: 'https://example.com/intro-video',
  },
  {
    id: 2,
    name: 'Prof. Amit Sharma',
    title: 'Engineering & Mathematics Expert',
    bio: 'Professor Amit Sharma brings 18 years of teaching experience in engineering mathematics and physics. His clear explanations and problem-solving techniques have made complex concepts accessible to thousands of JEE aspirants.',
    image: 'https://i.pravatar.cc/400?u=amit-sharma',
    expertise: ['Mathematics', 'Physics', 'Engineering', 'JEE Preparation'],
    experience: 18,
    students: 7200,
    courses: 15,
    rating: 4.8,
    totalReviews: 2100,
    education: ['B.Tech - IIT Delhi', 'M.Tech - IIT Bombay', 'PhD - Applied Mathematics'],
    certifications: ['IIT-JEE Expert', 'Advanced Mathematics Trainer'],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/amit-sharma',
      twitter: 'https://twitter.com/profamitsharma',
    },
    videoIntro: 'https://example.com/intro-video-2',
  },
]

export const mockBlogPosts: BlogPost[] = [
  {
    id: 1,
    title: '10 Proven Study Techniques for NEET Success',
    excerpt: 'Discover the most effective study methods that top NEET scorers use to ace their exams.',
    content: 'Full blog content here...',
    author: 'Dr. Rajesh Kumar',
    authorImage: 'https://i.pravatar.cc/100?u=rajesh',
    category: 'Exam Tips',
    tags: ['NEET', 'Study Tips', 'Medical'],
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=500&fit=crop',
    publishedDate: '2024-01-10T10:00:00',
    readTime: 8,
    views: 1520,
    featured: true,
  },
  {
    id: 2,
    title: 'JEE Main 2025: Complete Preparation Strategy',
    excerpt: 'A comprehensive guide to planning your JEE Main preparation from scratch.',
    content: 'Full blog content here...',
    author: 'Prof. Amit Sharma',
    authorImage: 'https://i.pravatar.cc/100?u=amit',
    category: 'Study Guides',
    tags: ['JEE', 'Engineering', 'Preparation'],
    image: 'https://images.unsplash.com/photo-1581092335331-5e00ac65e934?w=800&h=500&fit=crop',
    publishedDate: '2024-01-08T14:30:00',
    readTime: 12,
    views: 2340,
    featured: true,
  },
  {
    id: 3,
    title: 'From Zero to Hero: My NEET Journey',
    excerpt: 'A student shares their inspiring journey from average scores to NEET success.',
    content: 'Full blog content here...',
    author: 'Priya Patel',
    authorImage: 'https://i.pravatar.cc/100?u=priya',
    category: 'Success Stories',
    tags: ['Success Story', 'NEET', 'Motivation'],
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=500&fit=crop',
    publishedDate: '2024-01-05T09:00:00',
    readTime: 6,
    views: 3120,
    featured: false,
  },
]

export const mockLiveClasses: LiveClass[] = [
  {
    id: 1,
    title: 'Organic Chemistry - Reaction Mechanisms',
    description: 'Deep dive into organic reaction mechanisms with real-world examples',
    instructor: 'Dr. Rajesh Kumar',
    instructorImage: 'https://i.pravatar.cc/150?u=rajesh',
    subject: 'Chemistry',
    category: 'Medical',
    startTime: '2024-01-16T14:00:00',
    endTime: '2024-01-16T15:30:00',
    duration: 90,
    isRecorded: true,
    meetingLink: 'https://meet.ebodhak.com/organic-chem',
    maxParticipants: 100,
    currentParticipants: 78,
    status: 'upcoming',
  },
  {
    id: 2,
    title: 'Calculus - Integration Techniques',
    description: 'Master advanced integration methods for JEE Main',
    instructor: 'Prof. Amit Sharma',
    instructorImage: 'https://i.pravatar.cc/150?u=amit',
    subject: 'Mathematics',
    category: 'Engineering',
    startTime: '2024-01-16T16:30:00',
    endTime: '2024-01-16T17:30:00',
    duration: 60,
    isRecorded: true,
    meetingLink: 'https://meet.ebodhak.com/calculus',
    maxParticipants: 150,
    currentParticipants: 142,
    status: 'upcoming',
  },
  {
    id: 3,
    title: 'Physics - Electromagnetism Basics',
    description: 'Understanding electromagnetic fields and their applications',
    instructor: 'Dr. Sarah Johnson',
    instructorImage: 'https://i.pravatar.cc/150?u=sarah',
    subject: 'Physics',
    category: 'Engineering',
    startTime: '2024-01-15T10:00:00',
    endTime: '2024-01-15T11:30:00',
    duration: 90,
    isRecorded: true,
    recordingUrl: 'https://recordings.ebodhak.com/physics-em-basics',
    meetingLink: 'https://meet.ebodhak.com/physics-em',
    maxParticipants: 100,
    currentParticipants: 100,
    status: 'completed',
  },
]